### PR TITLE
Tom/implicit push

### PR DESCRIPTION
**Pull request by TomGoffrey**
@benmcmillanwarwick Marking this as WIP for now, as a few tasks remain:

 - [ ] Add implicit test to CI tests.
 - [ ] Possible modification of convergence criteria.
 - [ ] Check new push with more test cases.

The third item applies to the rest of the code too - I think we need to expand the sorts of tests we are doing. I'll be working on this over the next few weeks.

### CODE REVIEW

**Comment by benmcmillanwarwick** [comment]
OK, this all looks pretty good to me, and the implicit push code is pretty compact, which I guess shows that the refactoring did what it was meant to. As this is a WIP I'll hold off approving for the timebeing.

**Comment by TomGoffrey** [comment]
Hmm. I suspect the slightly higher growth rate I see with this push is due to the implicit push being non-relativistic. I see the same effect using a non-relativistic version of the Boris push in EPOCH.

**Comment by TomGoffrey** [comment]
See new issues #36 and #37 for the additional tasks.

**Comment by TomGoffrey** [comment]
@benmcmillanwarwick I've moved the additional tasks to new issues, so we can get this merge, ahead of the upcoming full implicit PIC merge request.

**Review by benmcmillanwarwick — APPROVED** [review]

**Pull request merged**
