### PR TITLE
Tom/input deck

### PR DESCRIPTION
**Pull request by TomGoffrey**
@benmcmillanwarwick Does this do everything you need?

In summary:

1. Added a Fortran namelist input deck which allows you to specify various control parameters at run time. See `Data/example_input.deck` for options and default values.
2. Added the ability to specify multiple problem set-ups. Each problem set-up can have it's own set of default control variables. See `two_stream_setup` in `src/user_interaction/ic_module.f90`.
3. The deck is read twice: Once to set the problem string, so that that problem's default control variable values can be set, and then a second time to allow the user to over-ride those options.
4. The input file is read on proc 0, and broadcast to other ranks. This seemed better than having all procs try and read from the same file at once.
5. If no input file is found the code resorts to the existing two-stream set-up.
6. I've left scope for setting problem specific field initialisations and boundary conditions in `src/housekeeping/setup.f90`, but haven't actually implemented anything.

Let me know if you have comments/questions/suggestions, otherwise I'll merge into main around 11:00 Friday 12th. If you are happy as is, feel free to merge before then.

### CODE REVIEW

**Comment by benmcmillanwarwick** [comment]
Hi Tom,
This looks OK: I guess another option is to split it into two namelists, one of which only has the 'problem' string, but I don't think this makes any practical difference. Possibly less confusing if things aren't done twice?

I guess the only thing the first call to problem_setup should be doing is setting problem-specific defaults for the namelist variables. I guess there isn't any consequence to things becoming inconsistent as long as the only thing you to in the first call to problem_setup is change variables that are in the namelist.

Anyway, works for me as written. Should be flexible enough to allow extra input variables.

**Comment by TomGoffrey** [comment]
Yes, that would also be an option. Essentially as proposed the code does:

```fortran
CALL read_deck ! Read problem
CALL set_parameters ! Initialise defaults
CALL read_deck ! Set non-default values
```

whereas what you're proposing there would just be a single `CALL read_deck` and inside read deck we'd have something like:

```fortran
SUBROUTINE read_deck
  ...
  READ(..., NML=problem, ...)
  CALL set_parameters
  READ(..., NML=control, ...)
  ...
END SUBROUTINE read_deck
```

I opted for the former purely because it involved the least amount of change to the existing structure. In hindsight, I'm not sure I like the proliferation of calling subroutines twice. Might be something to revisit.

**Comment by benmcmillanwarwick** [comment]
Yes, I somewhat prefer the option in your last comment, because it makes it clearer what is going on.

I agree that having procedures that have 'two modes' depending on how they are called makes things a bit harder to read and makes the flow harder to follow. But we can change it later without any damage: only important thing at the moment is to get the input file structure right.

**Comment by TomGoffrey** [comment]
@benmcmillanwarwick I've opened up an improvement issue to act as a reminder, but I agree it would be better to get this merged and push forward with deliverables.

**Comment by benmcmillanwarwick** [comment]
OK, sounds good, happy to 'improve' later

**Review by benmcmillanwarwick — APPROVED** [review]

**Pull request merged**
