### PR TITLE
Update README file

### PR DESCRIPTION
**Pull request by TomGoffrey**
Add details of EPOCH user manual, and link to EPOCH paper to README file.

### CODE REVIEW

**Review by benmcmillanwarwick — COMMENTED** [review]
I think an explicit link to the EPOCH user/developer manuals would help here.

**Comment by TomGoffrey** [comment]
Hmm, given there's already a link to EPOCH at the top of the file, I'm not sure adding a duplicate link in the `Further Details` section adds anything.

As the EPOCH manual is available from the minepoch repository (as a pdf), what's the benefit of linking to the EPOCH manual repo?

**Comment by benmcmillanwarwick** [comment]
Well, I don't know where this PDF manual is so I'm betting that the people at CCFE didn't find it either. Based on comments from CCFE they haven't managed to find any of the relevant papers/documentation.

I guess I think it is better in a "further information section" to include all of the relevant info, even if there is a link above. Put another way, what is the benefit to not linking to the EPOCH repository again?

**Comment by TomGoffrey** [comment]
There's no problem with linking again. As our code is "delivered" via releases, I assumed including the pdf of the manual with the releases (e.g. https://github.com/ExCALIBUR-NEPTUNE/minepoch/releases/tag/v1.1) was a sensible thing to do. We could link the page explicitly?

Edit to add: I added the manual pdfs in response to the comments from CCFE, so they would't have had it as part of the initial review.

**Comment by benmcmillanwarwick** [comment]
OK, I had missed that it was in the tag release. That's great but I obviously didn't see it so putting an explicit link in the README seems sensible. Having both the user and developer manual would be useful.

Basically, it seems safer to assume that people accessing minepoch are at least as clueless as I am (and e.g. don't even look at the tags) and make sure they can find the manuals from the README.

**Comment by TomGoffrey** [comment]
The release page is rather hidden away. I don't know how reasonable my assumption that the code will be accessed from there is.

I've added a link. Are you happy with the current version?

**Review by benmcmillanwarwick — APPROVED** [review]

**Pull request merged**
